### ISSUE TITLE
Add background image to workspace and app menu views

### ISSUE THREAD

**Issue by chrisjonesBSU** [axxapy/gnome-ui-tune#1]
I'm not sure if this extension is the right place to look for this feature, but it would be great if the background for these views wasn't a solid color, but instead a dimmed image of the current desktop background, which is how the workspace and app menu views were visualized in Gnome 3.

**Comment by axxapy** [comment]
Yeah, totally agree.
I am thinking for a couple days how to do that.
Problem is that gnome developers hard-removed code which was responsible for backgrounds in previews: https://github.com/GNOME/gnome-shell/commit/451ba5b03ad714366cb0ce6105cb775f84b051ba

The only way I see so far is to copy thumbnail object's code to the extension itself, fix it and swap original with fixed one in the memory.
But it could potentially break other extensions which could modify same object...

If I find safe solution, I'll definitely implement it.
Solid color looks terrible.

**Comment by axxapy** [comment]
I have pushed new version which restores background.
It will be available via extensions.gnome.org after review (usually takes day or two): https://extensions.gnome.org/review/23751
Or you can install by cloning this repo
