### ISSUE TITLE
Lots of padding between thumbnail and top bar.

### ISSUE THREAD

**Issue by CleoMenezesJr** [axxapy/gnome-ui-tune#12]
### How it is:
![Screenshot from 2021-10-20 21-47-41](https://user-images.githubusercontent.com/54215258/138192027-7bd81f69-1770-4d5e-a3d7-d498248aec87.png)
### How it could be:
![Screenshot from 2021-10-20 21-46-38](https://user-images.githubusercontent.com/54215258/138192029-f020d643-c664-4df9-a074-04d6096979cd.png)

**Comment by axxapy** [comment]
That's not how I see it on my primary display.
It would be great if you could open `lg` and make a PR with fix for this gap

![image](https://user-images.githubusercontent.com/3088476/167319188-449aade1-20a9-499d-b37f-cadfc7dbce48.png)

**Comment by CleoMenezesJr** [comment]
It's been a long time since I opened this issue, but I went to test it now and it works perfectly.
