### ISSUE TITLE
Clicking on empty workspace in thumbnails doesn't switch to it

### ISSUE THREAD

**Issue by sojusnik** [axxapy/gnome-ui-tune#16]
When clicking on an empty workspace in the thumbnails, then the current workspace is opened, rather than switching to the empty workspace.

Happens on Ubuntu 21.10 with Gnome 40.4.0 on X11.

**Comment by axxapy** [comment]
I can not reproduce this behaviour. Can you try to make a steps-to-reproduce video of gnome-boxes with fresh ubuntu installation and only my extensions enabled?

**Comment by sojusnik** [comment]
This was solved in Gnome 42.
