### ISSUE TITLE
Broken on Gnome 42 main / 42.beta with secondary monitor

### ISSUE THREAD

**Issue by VitalyAnkh** [axxapy/gnome-ui-tune#18]
After installing the latest gnome-shell and gjs, the extension reports `SecondaryMonitorDisplay is undefined`. I'm using a secondary monitor but this extension runs well with Gnome 40/41 until the lastest Gnome 42.

**Comment by axxapy** [comment]
Experimental support for gnome 42 has been released.
Closing this issue in favor of https://github.com/axxapy/gnome-ui-tune/issues/17

Not sure about secondary monitor display. Tested it on virtual machine but did not get stable results.
Please let me know how it works for you in https://github.com/axxapy/gnome-ui-tune/issues/17
