### ISSUE TITLE
Feature Request: Add "Window is Ready" Notification remover too within this extension 

### ISSUE THREAD

**Issue by realKarthikNair** [axxapy/gnome-ui-tune#22]
Basically, if the features of [this](https://extensions.gnome.org/extension/1007/window-is-ready-notification-remover/) extension too could be added to Gnome 4x UI Improvements, it would be nice.

code reference: https://github.com/nunofarruca/WindowIsReady_Remover/blob/master/windowIsReady_Remover%40nunofarruca%40gmail.com/extension.js

**Comment by axxapy** [comment]
Extension you're referring to is more about UX than UI. 
May I ask, why do you want to incorporate it? What's wrong with installing both extensions?
