### ISSUE TITLE
Remove gnome 42 support tag while it's not ready

### ISSUE THREAD

**Issue by redpandamonium** [axxapy/gnome-ui-tune#25]
Distros have shipped version 42 along with this extension (likely because the metadata of this extension says it is supported), while the extension doesn't support 42. The 42 support should be removed from the metadata until it is fixed so people actually get an error instead of having to figure out themselves why their UI looks broken.

**Comment by seitbekir** [comment]
It works on my Gnome 42, but only after switch off/on. When computer starting with this extension it shows gray background instead of desktops. But fixing after restart. Seems like it has minor issue, but I don't see something special in logs (it is huge).

**Comment by axxapy** [comment]
It works well on arch that I'm using. No issues whatsoever.
If someone could make a case to reproduce, lets say, in virtual machine, I might be able to fix it

**Comment by n3thshan** [comment]
> It works well on arch that I'm using. No issues whatsoever. If someone could make a case to reproduce, lets say, in virtual machine, I might be able to fix it

try using this extension with dash to dock and bam u have the issue!

**Comment by axxapy** [comment]
#17
