### ISSUE TITLE
Workspaces are only visible after second workspace have something on it

### ISSUE THREAD

**Issue by snaggen** [axxapy/gnome-ui-tune#3]
When I just have logged in and start applications, I would like to drag and move things to the workspaces, but they are not shown. I would have the workspaces always visible.

**Comment by axxapy** [comment]
That's the default gnome-shell behavior.
there is separate extension to always show thumbnails:
https://extensions.gnome.org/extension/4156/always-show-workspace-thumbnails/

I'll keep this issue open as I'll probably incorporate this functionality among with settings screen where this behavior could be configured

**Comment by emansom** [comment]
> When I just have logged in and start applications, I would like to drag and move things to the workspaces, but they are not shown. I would have the workspaces always visible.

Dragging the window to the right instead of up solves this use-case.

**Comment by axxapy** [comment]
I have added setting (enabled by default) which does this.
Will be available by auto-update after review is done: https://extensions.gnome.org/review/24935
