### ISSUE TITLE
PIP mod only works for English language

### ISSUE THREAD

**Issue by niezywa** [axxapy/gnome-ui-tune#32]
The PIP mode just doesn't seem to work on my system. After studying the code, I found out it's due to the window title depending on Firefox language setting.

Line 11 src/modFirefoxPipInOverview.js
`            if (win.title && win.title === 'Picture-in-Picture') {`

![Zrzut ekranu z 2023-01-22 03-05-55](https://user-images.githubusercontent.com/104802727/213898756-b7aa6ad8-cb24-4515-bbb9-3a863b51fb5d.png)

**Comment by axxapy** [comment]
Fair enough. Any suggestions how to make it language-agnostic?

**Comment by niezywa** [comment]
I'll try looking into this in my free time, but right now I can only think of the most obvious solution and it might be impractical to implement. I can't really see a way to distinguish that window. We could pull in the firefox l10n files, at least only the relevant ones. They're on Mozilla's mercurial; e.g. the relevant file for Arabic is here: [toolkit/toolkit/pictureinpicture/pictureinpicture.ftl](https://hg.mozilla.org/l10n-central/ar/file/tip/toolkit/toolkit/pictureinpicture/pictureinpicture.ftl) . From there we're interested in line:
`pictureinpicture-player-title = ڤديو معترِض`
I don't think it makes sense to use fluent.js just for this, so my feeling is that would be a regex, but I'm not a great programmer :stuck_out_tongue: . Also, I'm not 100% sure it's a fair assumption that the Firefox language will match up to system locale.

**Comment by axxapy** [comment]
This is actually a pretty good workaround.

I created a draft 795bf6e9167f39e318e497ecae7fb8a06280cab3

Since I don't have gnome 4x right now to test, would you mind testing [gnome-ui-tune@itstime.tech.shell-extension.zip](https://github.com/axxapy/gnome-ui-tune/files/11217688/gnome-ui-tune%40itstime.tech.shell-extension.zip)?

(just replace installed extension in `~/.local/share/gnome-shell/extensions/gnome-notification-center@itstime.tech` and do signout=>signin)

**Comment by niezywa** [comment]
I just tested this and I'm not really sure if this works. To be honest, I'm now not exactly sure what this feature was supposed to accomplish, as even with Firefox language set to English, no version of this extension seems to do anything when the setting is on :$.

**Comment by axxapy** [comment]
Fixed in the [latest release](https://github.com/axxapy/gnome-ui-tune/releases/tag/v1.7.4).
Thanks for your suggestion
