### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [axxapy/gnome-ui-tune#35]
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by mikicvi** [comment]
#30 Still present in gnome 44. Using Fedora 38 with Dash to Dock and a couple of other extensions. 

Tested for this even with only this extension enabled, and am receiving the very same outcome.

Likely not relevant:
Hardware: Dell XPS 13 9310
OS: Fedora Linux 38 Gnome
Kernel: 6.4.15-200.fc38.x86_64

**Comment by failafail8** [comment]
the #29 and #30 issues are on Gnome44 right ? having a 720p screen i'm rlly lookin into that g45 branch when u have time ofc , thank you 


> #30 Still present in gnome 44. Using Fedora 38 with Dash to Dock and a couple of other extensions.


dashtoPanel is the solution 😝

**Comment by joaoluizcarvalho** [comment]
I tried to install it on Fedora 39 (beta) from https://extensions.gnome.org/extension/4158/gnome-40-ui-improvements/, but the extension is marked as incompatible. Current Gnome Shell version is 45.0.

**Comment by bulletmark** [comment]
Arch Linux updated to GNOME 45 today so this is an issue for many more users.

**Comment by bulletmark** [comment]
Note the functions of this extension that I, and probably many others here, really want are (from the main README):

- Search textbox is hidden by default and shown only when user begins to type-to-search.
- Scale of workspaces thumbnails increased 2x.
- Show workspaces' thumbnails even when there is only one workspace.

I don't really care about the workspace image or the firefox PIP.

Given this extension does not support GNOME 45, I have changed to the [Just Perfection](https://extensions.gnome.org/extension/3843/just-perfection/) extension which provides all these functions and **does work** with GNOME 45.

**Comment by axxapy** [comment]
Support for Gnome 45 has been released. Closing.
