### ISSUE TITLE
GNOME 47 support

### ISSUE THREAD

**Issue by Jai-JAP** [axxapy/gnome-ui-tune#41]
Looks like there are no breaking changes needed for the extension to work.

Just adding 47 to `shell-version` in `metadata.json` makes it work flawlessly.
https://github.com/axxapy/gnome-ui-tune/blob/738bb6781afce230684203d30624e4bdf33ab219/metadata.json#L7

**Comment by bulletmark** [comment]
GNOME 47 is released in stock Arch packages from today so this change is somewhat pressing.

**Comment by Tyrbiter** [comment]
Fedora 41 beta has GNOME 47 so it would be nice to have an official update, but the metadata.json hack works too.

**Comment by axxapy** [comment]
Released
