### ISSUE TITLE
Gnome 40 UI Improvements extension is on but don't works

### ISSUE THREAD

**Issue by difrkaguilar** [axxapy/gnome-ui-tune#5]
In Fedora 34 every time turn the system on  the Gnome 40 UI Improvements extension is on but don't works. 
I've to open the Extensions app, then turn off an on the extension and then works.

This is my system configuration:

OS: Fedora 34 (Workstation Edition) x86_64 
Host: Z390 AORUS MASTER 
Kernel: 5.11.18-300.fc34.x86_64 
Uptime: 1 hour, 10 mins 
Packages: 2313 (rpm), 6 (flatpak), 10 (snap) 
Shell: zsh 5.8 
Resolution: 3840x2160 
DE: GNOME 40.0 
WM: Mutter 
WM Theme: Adwaita 
Theme: Materia-dark-compact [GTK2/3] 
Icons: Os-Catalina-icons-master [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-9700K (8) @ 4.900GHz 
GPU: NVIDIA GeForce GTX 1070 
GPU: NVIDIA GeForce GTX 1080 Ti 
Memory: 3662MiB / 32037MiB

**Comment by axxapy** [comment]
Strange.
I guess some other extension possibly breaks it.

Could you please attach output of:
- `journalctl -b /usr/bin/gnome-shell`
- `gnome-extensions list --enabled`

----

Also what you could try to do is: 
1. disable all extensions
2. restart gnome-shell (login/logout or alt+f2 => r, if you're not on wayland)
3. enable this (gnome 40 ui tune) extension
4. test if it works after restart
5. if yes, enable other extensions one-by-one (enable one => reboot => see if everything is okay => enable another => ...repeat).

This ^^ will let you find which extension is responsible for that inconvenience.

**Comment by difrkaguilar** [comment]
I found the issue, the Just Perfection extension override the Gnome 40 UI extension. Just Perfection in the visibility options force the grnome-shell to show the search box. 

If users like to have this two extensions working, then they have to turn the search visibility off in the Just Perfection extension.

![Screenshot-20210514112443-687x995](https://user-images.githubusercontent.com/67672868/118294032-4defd200-b4a8-11eb-9424-0bfc904ff740.png)

**Comment by axxapy** [comment]
Yeah, these two extensions change same part of the gnome. It makes sense that they're in conflict.

Do I understand you right that you use "Just perfection" to restore search box which is hidden by my extension?
If yes, the latest version (which was released yesterday) has settings where you can choose whether to hide search box or not:
<img src=https://user-images.githubusercontent.com/3088476/118346959-84136d00-b50d-11eb-954c-99b0e3c16323.png width=400px> 

I believe that if you disable "Hide search" mod, `Just perfection` will stop being a problem

**Comment by difrkaguilar** [comment]
> I believe that if you disable "Hide search" mod, `Just perfection` will stop being a problem

Yes I did that. Thanks for the improvements
