### ISSUE TITLE
Customizing the size of workspace thumbnails

### ISSUE THREAD

**Issue by LeFloatyPancake** [axxapy/gnome-ui-tune#8]
I was looking for a way to be able to customize the size of the workspace thumbnails. Is there any other way to set the workspace thumbnails to 1.7x -1.9x?

Great job with the extension mate.

**Comment by axxapy** [comment]
you can manually adjust it on your installed copy
It won't survive extension update but It does not happen often, so could be a solution for you

Installed extensions are located in `~/.local/share/gnome-shell/extensions/` directory

You need to change the following line:
https://github.com/axxapy/gnome-ui-tune/blob/8bfc971/src/modScaleThumbnails.js#L10

**Comment by LeFloatyPancake** [comment]
Took a while to find the right scale size but finally got it. Thanks.
